# Generated by Django 4.2 on 2023-10-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orden',
            new_name='Ordenes',
        ),
    ]
