# Generated by Django 4.2 on 2023-10-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_rename_orden_ordenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
