# Generated by Django 4.2 on 2023-10-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_alter_clientes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descrip',
            field=models.TextField(blank=True),
        ),
    ]
