# Generated by Django 4.2 on 2023-10-20 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MiApp', '0006_productos_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientes',
        ),
        migrations.AlterField(
            model_name='user1',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
